SendToConsole("say Welcome to Portal 2 Co-op!")
SendToConsole("say Introduction:")
SendToConsole("say Welcome to Portal 2 Co-op, where collaboration is key. Work together to solve puzzles and conquer challenges.")
SendToConsole("say Communication:")
SendToConsole("say 1. Voice Chat: Use voice chat for efficient communication.")
SendToConsole("say 2. Ping System: Ping objects or locations to get your partner's attention.")
SendToConsole("say 3. Text Chat: Use text chat when necessary, but keep messages clear and concise.")
SendToConsole("say Collaboration Tips:")
SendToConsole("say 1. Listen Actively: Pay attention to your partner's ideas.")
SendToConsole("say 2. Plan Together: Discuss strategies and roles before attempting puzzles.")
SendToConsole("say 3. Be Patient: Mistakes happen, provide constructive feedback.")
SendToConsole("say 4. Celebrate Success: Acknowledge achievements together.")
SendToConsole("say Additional Guidelines:")
SendToConsole("say 5. Explore Together: Take time to explore and discover hidden areas. You may find secrets and shortcuts.")
SendToConsole("say 6. Share Knowledge: If you have experience with a puzzle, share hints or tips, but avoid spoilers.")
SendToConsole("say 7. Stay in Sync: Coordinate your actions, especially when timing is crucial.")
SendToConsole("say 8. Be Open to Suggestions: Be open to trying your partner's ideas, even if they seem unconventional.")
SendToConsole("say 9. Enjoy the Story: Portal 2 has a rich narrative. Take time to enjoy the storyline together.")
SendToConsole("say Pings:")
SendToConsole("say - Thumbs Up Ping: This ping means 'Good job!' It's a way to show appreciation for your partner's actions or solutions.")
SendToConsole("say - Thumbs Down Ping: This ping can convey two messages. It can mean 'You're doing very bad right now,' or if placed on a portalable surface, it can indicate 'Don't place a portal here.' Use it thoughtfully.")
SendToConsole("say - Question Mark Ping: The question mark ping represents curiosity. It can mean 'I wonder what this is?' or 'Try this, it might help.' It's an invitation to explore and experiment.")
SendToConsole("say - '?!*' Ping: The '?!*' ping expresses frustration or being stuck. It can convey 'I'm very mad right now' or 'I'm stuck and need assistance.' It's a way to communicate when things aren't going well.")
SendToConsole("say - Portal with a Line Through It Ping: This ping simply means 'Don't place a portal here.' It's a way to prevent unnecessary portal placement and convey that a particular location is not suitable for portals.")
SendToConsole("say Standard Pings:")
SendToConsole("say - Blue Ping: The blue ping marks a location or object with a blue indicator. It's a way to draw your partner's attention to a specific point.")
SendToConsole("say - Orange Ping: The orange ping is equivalent to the 'look' command in the Source engine. Use it to direct your partner's attention to something specific.")
SendToConsole("say - Countdown Ping: The countdown ping is used to start a countdown from 3 to 1. It's helpful for timing actions or coordination.")
SendToConsole("say - Go Ping: The 'Go' ping signifies the start of an action or sequence. While it can be used manually, it requires modifying your game settings.")
SendToConsole("say Conclusion:")
SendToConsole("say Portal 2 Co-op rewards collaboration and communication. Enjoy the adventure together!")
SendToConsole("say Press 'T' to talk/respond and view chat history.")
