scns_movie_display <- Entities.CreateByClassname("vgui_movie_display")
ppmod.addoutput(scns_movie_display,"angles",FindByEntIndex(1).GetAngles())
ppmod.addoutput(scns_movie_display,"forcedslave",0)
ppmod.addoutput(scns_movie_display,"forceprecache",0)
ppmod.addoutput(scns_movie_display,"height",128)
ppmod.addoutput(scns_movie_display,"looping",1)
ppmod.addoutput(scns_movie_display,"width",320)
ppmod.addoutput(scns_movie_display,"moviefilename","media/attract01.bik")
ppmod.addoutput(scns_movie_display,"targetname",UniqueString("scns_movie_display"))
ppmod.addoutput(scns_movie_display,"stretch",1)
ppmod.fire(scns_movie_display,"setparent","blue")
ppmod.fire(scns_movie_display,"enable")